# Generated by Django 4.2.16 on 2024-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaDeTarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='feito',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
